AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an S3 bucket 
Resources:
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 
              - 's3.PutBucketPolicy'
            Resource: 'arn:aws:s3:::ansh32'
      Bucket: 'ansh32'