AWSTemplateFormatVersion: "2010-09-09"
Description: "Pseudo Parameters"

Parameters:
  Envronment:
    Type: String
    AllowedValues:
      - dev
      - prod
      - qa
Mappings:
  EnvMap:
    dev:
      instanceType: "t2.micro"
      name: "dev"
    qa:
      instanceType: "t2.medium"
      name: "qa"
    prod:
      instanceType: "t2.xlarge"
      name: "prod"

Conditions:
  CreateProdResources: !Equals [ !Ref Envronment, prod ]

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [EnvMap, !Ref Envronment, instanceType]
      ImageId: ami-026b57f3c383c2eec
      Tags:
        - Key : "Name"
          Value: !FindInMap [EnvMap, !Ref Envronment, name]

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Condition: CreateProdResources
    Properties:
      InstanceId: 
        !Ref Instance
      VolumeId: 
        !Ref NewVolume
      Device: /dev/sdh

  NewVolume:
    Type: AWS::EC2::Volume
    Condition: CreateProdResources
    Properties:
      Size: 100
      AvailabilityZone: 
        !GetAtt Instance.AvailabilityZone

Outputs:
  InstanceName:
    Value: !Ref Instance