AWSTemplateFormatVersion: "2010-09-09"
Description: "Create s3 bucket"
Resources:
  S3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hfkjshfjkfh
Outputs:
  BucketName:
    Value: !Ref S3bucket
    !GetAtt S3.Arn